# Generated by Django 3.1.4 on 2021-01-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantData',
            new_name='Applicant',
        ),
    ]
