# Generated by Django 3.1.6 on 2021-02-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('domain', models.CharField(choices=[('PR', 'PR'), ('Sponsorship', 'Sponsorship'), ('Shows', 'Shows'), ('Workshop', 'Workshop'), ('Culti', 'Culti'), ('Biggies', 'Biggies'), ('Techy', 'Techy'), ('Social Cause', 'Social Cause'), ('Informals', 'Informals'), ('Miscellaneous', 'Miscellaneous'), ('Finance', 'Finance'), ('Merch', 'Merch')], max_length=45)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ELANRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('institute', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
