# Generated by Django 2.2.17 on 2021-01-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=45)),
                ('institute', models.CharField(max_length=200)),
            ],
        ),
    ]
